### ISSUE TITLE
webpack.dev.conf.js is not exist

### ISSUE THREAD

**Issue by OlimCarl** [Amsterdam/mlvb#22]
I tried to run frontend module, but there isn't exist "webpack.dev.conf.js" file.
I think it cause .gitignore file.
Would you please upload build directory including webpack config file?

Thanks.

**Comment by Lytrix** [comment]
@OlimCarl Thanks for catching that bug. I removed the build folder from the .gitignore so it is added now to the repo. It should find the missing files now.

**Comment by OlimCarl** [comment]
Thank you for quick response!
